# [rust]
# # path of rust contracts workspace directory,
# # a `Cargo.toml` file is expected under the directory.
# workspace_dir = "."
# toolchain = "nightly-2021-08-16"
# docker_image = "thewawar/ckb-capsule:2021-08-16"

# capsule version
version = "0.7.0 56bf934"
# path of deployment config file
deployment = "deployment.toml"

[[nervos-scripts]]
name = "issuer-type"
template_type = "Rust"

[[nervos-scripts]]
name = "class-type"
template_type = "Rust"

[[nervos-scripts]]
name = "nft-type"
template_type = "Rust"

[[nervos-scripts]]
name = "metadata"
template_type = "Rust"
