[workspace]
members = ["nervos-scripts/issuer-type", "nervos-scripts/class-type", "nervos-scripts/nft-type", "nervos-scripts/metadata","tests"]

[profile.release]
overflow-checks = true
opt-level = 's'
lto = true
codegen-units = 1
panic = 'abort'
